"""Dataclass DTOs — the API models of stapel-forms (never ORM instances).

Model-backed DTOs are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); the hand-written
dataclasses here are the envelopes with no single backing model.

``PublicFormDTO`` is a DEDICATED envelope, not the admin one with fields
removed. Dropping fields is how leaks happen the day somebody adds a field
to the admin shape and nobody remembers the public serializer inherits it:
this one has no workspace, no internal id, no author, no counts, no
siblings — because it never had them.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class PublicFormDTO:
    """What an anonymous respondent is allowed to know about a form."""

    public_id: str
    version_id: str
    version: int
    fields: List[Dict[str, Any]] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SubmitResultDTO:
    """The whole answer to a successful submit.

    Deliberately not the submission id: there is no public read of
    submissions, and handing out an identifier for a resource nobody may
    fetch only invites people to try.
    """

    accepted: bool = True
    confirmation: str = ""


@dataclass
class PublishResultDTO:
    version_id: str
    version: int
    published_at: str


@dataclass
class SubmissionPageDTO:
    """One keyset page of responses plus the cursor for the next one."""

    items: List[Any] = field(default_factory=list)
    next_before: Optional[str] = None


@dataclass
class ResendResultDTO:
    sent: int


__all__ = [
    "PublicFormDTO",
    "SubmitResultDTO",
    "PublishResultDTO",
    "SubmissionPageDTO",
    "ResendResultDTO",
]
