"""Dataclass DTOs — the API models of stapel-forms (never ORM instances).

Model-backed DTOs are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); the hand-written
dataclasses here are the envelopes with no single backing model.

``PublicFormDTO`` is a DEDICATED envelope, not the admin one with fields
removed. Dropping fields is how leaks happen the day somebody adds a field
to the admin shape and nobody remembers the public serializer inherits it:
this one has no workspace, no internal id, no author, no counts, no
siblings — because it never had them.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class PublicFormDTO:
    """What an anonymous respondent is allowed to know about a form."""

    public_id: str
    version_id: str
    version: int
    fields: List[Dict[str, Any]] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SubmitResultDTO:
    """The whole answer to a successful submit.

    Deliberately not the submission id: there is no public read of
    submissions, and handing out an identifier for a resource nobody may
    fetch only invites people to try.
    """

    accepted: bool = True
    confirmation: str = ""


@dataclass
class PublishResultDTO:
    version_id: str
    version: int
    published_at: str


@dataclass
class SubmissionPageDTO:
    """One keyset page of responses plus the cursor for the next one."""

    items: List[Any] = field(default_factory=list)
    next_before: Optional[str] = None


@dataclass
class ResendResultDTO:
    sent: int


@dataclass
class FieldKindDTO:
    """One field kind the builder may offer, with its config form.

    ``fields`` is stapel-attributes' own ``config_form()`` declaration,
    passed through verbatim (``FormField.to_dict()`` shape: ``name``,
    ``kind``, ``label_key``, optional ``required`` / ``default`` /
    ``params``) — this module does not re-shape upstream's contract, so a
    kind gains config fields upstream without a release here.

    ``registered`` is FALSE for a kind the host allowlisted that the
    attributes registry does not carry. It is still listed, because a
    stored schema may already use it and a builder that silently drops the
    kind would silently drop the field.
    """

    kind: str
    label_key: str
    allowed: bool
    registered: bool
    fields: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class FieldKindsDTO:
    """The whole field-kind catalogue behind the builder.

    ``config_widgets`` is upstream's ``config_form.FIELD_KINDS``: the
    *widget* vocabulary a declaration's ``kind`` draws from, mapped to the
    params each widget understands. Named apart from ``kinds`` on purpose —
    forms' own ``FIELD_KINDS`` setting is the feature-type allowlist, and
    two different things called the same name is how a builder ends up
    rendering a ``number`` where a ``string`` belongs.
    """

    kinds: List[FieldKindDTO] = field(default_factory=list)
    config_widgets: Dict[str, List[str]] = field(default_factory=dict)


__all__ = [
    "PublicFormDTO",
    "SubmitResultDTO",
    "PublishResultDTO",
    "SubmissionPageDTO",
    "ResendResultDTO",
    "FieldKindDTO",
    "FieldKindsDTO",
]
