"""Serializers for the stapel-forms API.

Model-backed response serializers are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); request serializers and
non-model envelopes live here.

The module-level ``FormSerializer``/``FormVersionSerializer``/
``SubmissionSerializer`` names resolve the ACTIVE presenter once at import
time — a ``STAPEL_SWAP`` override lands in both the schema and the runtime
because settings are fixed before this module loads.
"""
from __future__ import annotations

from rest_framework import serializers
from stapel_core.django.api.serializers import StapelDataclassSerializer

from .dto import (
    FieldKindsDTO,
    PublicFormDTO,
    PublishResultDTO,
    ResendResultDTO,
    SubmitResultDTO,
)
from .presenters import (
    get_form_presenter,
    get_submission_presenter,
    get_version_presenter,
)

FormSerializer = get_form_presenter().serializer_class()
FormVersionSerializer = get_version_presenter().serializer_class()
SubmissionSerializer = get_submission_presenter().serializer_class()


# ── Envelope responses ───────────────────────────────────────────────


class PublicFormSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = PublicFormDTO


class SubmitResultSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = SubmitResultDTO


class PublishResultSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = PublishResultDTO


class ResendResultSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = ResendResultDTO


class FieldKindsSerializer(StapelDataclassSerializer):
    """The builder's field-kind catalogue (``FieldKindsDTO``)."""

    class Meta:
        dataclass = FieldKindsDTO


# ── Requests ─────────────────────────────────────────────────────────


class WorkspaceQuerySerializer(serializers.Serializer):
    workspace_id = serializers.UUIDField()


class FormListQuerySerializer(WorkspaceQuerySerializer):
    state = serializers.ChoiceField(
        choices=["draft", "open", "closed"], required=False, allow_null=True
    )


class FormCreateSerializer(serializers.Serializer):
    workspace_id = serializers.UUIDField()
    title = serializers.CharField(max_length=255)
    settings = serializers.DictField(required=False)
    draft_schema = serializers.JSONField(required=False)


class FormPatchSerializer(serializers.Serializer):
    title = serializers.CharField(max_length=255, required=False)
    settings = serializers.DictField(required=False)


class DraftSerializer(serializers.Serializer):
    schema = serializers.JSONField()


class StateSerializer(serializers.Serializer):
    state = serializers.ChoiceField(choices=["draft", "open", "closed"])


class SubmissionListQuerySerializer(serializers.Serializer):
    """Paging cursor, date window and value search.

    ``before`` (paging) and ``since``/``until`` (filtering) are separate
    parameters on purpose — see ``services.list_submissions``.
    """

    before = serializers.DateTimeField(required=False)
    limit = serializers.IntegerField(required=False, min_value=1)
    version = serializers.IntegerField(required=False, min_value=1)
    since = serializers.DateTimeField(required=False)
    until = serializers.DateTimeField(required=False)
    q = serializers.CharField(required=False, allow_blank=True)
    field = serializers.CharField(required=False, allow_blank=False)


class SubmitSerializer(serializers.Serializer):
    """The anonymous submit body.

    ``version_id`` is what the client echoes back from the schema it
    rendered — it is what makes a racing publish a clean 409 instead of a
    silent mis-validation. ``captcha_token`` is the seam the pair fills:
    the netintel tier decides whether a token is required at all, so it
    stays optional here and the captcha layer refuses on its own terms.
    """

    answers = serializers.JSONField()
    version_id = serializers.UUIDField(required=False, allow_null=True)
    captcha_token = serializers.CharField(required=False, allow_blank=True)


class ResendSerializer(serializers.Serializer):
    """Optional destination override for a resend.

    Given either list, the form's own configured targets are replaced, not
    supplemented: "send this one to legal" must not also re-send it to
    everyone who already has it.
    """

    recipients = serializers.ListField(
        child=serializers.EmailField(), required=False, allow_empty=True
    )
    telegram_chat_ids = serializers.ListField(
        child=serializers.CharField(max_length=64), required=False, allow_empty=True
    )


__all__ = [
    "FormSerializer",
    "FormVersionSerializer",
    "SubmissionSerializer",
    "PublicFormSerializer",
    "SubmitResultSerializer",
    "PublishResultSerializer",
    "ResendResultSerializer",
    "FieldKindsSerializer",
    "WorkspaceQuerySerializer",
    "FormListQuerySerializer",
    "FormCreateSerializer",
    "FormPatchSerializer",
    "DraftSerializer",
    "StateSerializer",
    "SubmissionListQuerySerializer",
    "SubmitSerializer",
    "ResendSerializer",
]
