# Generated by Django 6.0.8 on 2026-08-21 02:48

import django.db.models.deletion
import stapel_forms.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('public_id', models.CharField(db_index=True, default=stapel_forms.models.generate_public_id, max_length=32, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('draft_schema', models.JSONField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forms_form',
            },
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('schema', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forms.form')),
            ],
            options={
                'db_table': 'forms_form_version',
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='form',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forms.formversion'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('submitted_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_meta', models.JSONField(blank=True, null=True)),
                ('erased_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.formversion')),
            ],
            options={
                'db_table': 'forms_submission',
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='formversion',
            constraint=models.UniqueConstraint(fields=('form', 'version'), name='forms_version_unique'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['workspace_id', 'state'], name='forms_form_ws_state'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['form', '-submitted_at'], name='forms_sub_form_time'),
        ),
    ]
